rss.py, rss.xml
* rss.py generates rss.xml from all torrents in the directory
* rss.py requires pypy modules
* rss.xml has been tested in gecko and chromium for validity as well as w3c.
* rss.xml complies with the draft http://www.bittorrent.org/beps/bep_0036.html
Relates to #369
=> Added RSS Feed (for torrents)

_pages/Region-Changing.md
Added an extra step for the FBI prompt about installing tickets from CDN. This option should be declined to prevent running into errors while importing tickets.
=> Decline installing from CDN in section VII

_pages/DSiWare-Downgrade.md
Steelax is unnecessary if the user already owns an entrypoint (which is not unlikely, if the already have a modded console) and only introduces unnecessary steps and unreliability in such cases.
=> Skip Steelhax if you have another entrypoint

_pages/DSiWare-Downgrade-(Save-Injection).md
Simply removes an extra word from the DSiWare Downgrade (Save Injection) page (which shouldn't be there)
=> Remove extra word from DSiWare Save Inject

_pages/en_US/2.1.0-ctrtransfer.txt, _pages/en_US/Installing-arm9loaderhax.txt
Added extra clarification on how to re-enable wifi on 2DS and n3DS for people who are misunderstanding the troubleshooting step and leaving the AC charger plugged in.
=> Clarification on re-enabling wifi 

_pages/en_US/Installing-arm9loaderhax.txt
Removing the 'not functional on 11.3.0' warning as it is now functional on 11.3 provided that the person has the new *hax payload and hblauncher_loader v1.13.
=> Remove 'not working currently' warning for HBL

_pages/en_US/Updating-A9LH.txt
Added + This breaks the Homebrew Launcher on 11.3! since it's missed (thanks Still for this!)
=> Missed string about HBL on 11.3

_pages/en_US/Troubleshooting.txt
The "Restore SysNAND (safe)" in GodMode9 is only available when running from a9lh. When not running from a9lh the backup has to be restored by copying it to SysNAND Virtual.
Because of a bug in the current release of GodMode9 (v1.0.7), they key combo to unlock lvl3 writing is currently not required. This will be fixed in the next release.
=> Fixed instructions after a failed CTRTransfer

_pages/en_US/Updating-to-Boot9Strap.txt
As per the above steps of the guide, when you go to [https://github.com/KunoichiZ/lumaupdate/releases/latest](https://github.com/KunoichiZ/lumaupdate/releases/latest) what is offered is a direct download of lumaupdater-v2.0.cia and not as part of a .zip file.
=> Update "Updating to Boot9Strap" page

_pages/en_US/Installing-Boot9Strap-(Browser).txt
Some browser versions require Launcher.dat in conjunction with the alternative URLs.
A PR has been submitted for SafeB9SInstaller: https://github.com/d0k3/SafeB9SInstaller/pull/3
=> Add alternative URLs for launching SafeB9SInstaller via browser

_pages/en_US/Installing-Boot9Strap-(Browser).txt
There is no release containing the SafeB9SInstaller `Launcher.dat` yet. This will be re-added when a new release is made.
=> Revert "Add alternative URLs for launching SafeB9SInstaller via browser"

_pages/en_US/finalizing-setup.txt
Recent Luma3DS updates make it that having only one payload launches directly to that payload when holding (Start). This also removes some unnecessary reboots.
=> Make Finalizing Setup less redundant

_pages/en_US/finalizing-setup.txt
Users will not need these CIAs after installing them, and can save room by deleting them in the install process.
=> Delete CIAs after install

_pages/en_US/finalizing-setup.txt
Luma configuration already creates this folder with config.bin on the previous step and currently causes a double folder to be made
=> Remove double folder creation

_pages/en_US/finalizing-setup.txt
I don't really see the point of downloading the `.zip` files if we only need the `.cia` files.
=> Remove unnecessary unzipping

_pages/en_US/finalizing-setup.txt, _pages/en_US/troubleshooting.txt
Changes in > troubleshooting.txt (Also mentioned to keep "firmware.bin" for luma v7.1 or lesser)
Changes in > finalizing-setup.txt (firmware.bin changed to native.firm for latest luma compatibility)
=> "firmware.bin" changed to "native.firm" for Luma3DS v8.0

_pages/en_US/installing-boot9strap-(2xrsa).txt
The text for restoring your NAND is outdated. Section II is now "Updating the System" and Section III is "Launching FBI". "Configuring Luma3DS" has moved to this page altogether. (From what I understand) the NAND restore should be done at this point
=> Fix 2xrsa NAND restore text

_pages/en_US/region-changing.txt
I experienced this issue with my New 2DS LL (JPN) and saw some other people had had similar issues in the past. This is apparently from "qtm" breaking? Updating fixed it for me and others, but I needed a way to boot into the system to update.
=> fix for potential boot error after ctr transfer

_pages/en_US/flashing-ntrboot-(custom-firmware).txt, _pages/en_US/installing-boot9strap-(ntrboot).txt
This will help with confusion a bit, not needing to jump between pages.
This also places them in the right place, so that users will not have to worry about keeping track of when to restore their flashcarts.
Sorry for the incredibly long commit message :P
=> Move the instructions on removing ntrboot to the `Installing boot9strap` page

_pages/en_US/installing-boot9strap-(dsiware-game-injection).txt
When using 4swordshax (Japanese sudokuhax) the boot.nds error is replaced with a white screen. Some people are confused when they dont see the error and think the exploit has failed so it is a good idea to add a note about this. Previously this was only present for save injection's guide page but it is the case for game injection aswell.
=> Add that white screen may appear instead of boot.nds error for game injection

_pages/en_US/flashing-ntrboot-(3ds-single-system).txt, _pages/en_US/ntrboot.txt
Nintendo has not updated anything to block cards since 7.0.0-X, so these cards should work on the latest too.
=> update max vers for Infinity 3 R4i

gm9_scripts/uninstall_hax_retail_NEW.gm9, gm9_scripts/uninstall_hax_retail_OLD.gm9
The current script uses `find` without parameters, which gets the alphanumerical last match since GodMode9 v1.4.0. This causes the script to, if present, flash the firm of a predownloaded update. Using the `-f` flag (alphanumerical first match) ensures the oldest firm available is used, which should always be the currently installed one.
I also added a `-w` flag (force overwrite) when copying the firm to `gm9/out` to prevent the user from skipping/renaming the firm if the file already exists, which could also cause a wrong firm to be installed.
=> Uninstall CFW: Use correct NATIVE_FIRM version

_pages/en_US/region-changing.txt, _pages/en_US/troubleshooting.txt
This pull request fixes the issue of https://3ds.guide/troubleshooting and https://3ds.guide/region-changing both having an **extra** period at the end of their torrent notices.
=> Remove unnecessary punctuation

_pages/en_US/a9lh-to-b9s.txt
I reverted a9lh-to-b9s.txt to how it was on https://github.com/Plailect/Guide/commit/32680e2d4d5d5226748517e47f15f4f15b99513a
Admittedly I did not think about old versions of a9lh that aren't able to boot `arm9loaderhax_si.bin` payloads. Perhaps this can be looked at in the future if/when SafeB9SInstaller has built-in screen init. For the time being, the guide will have to stay as it is.
I also modified it a bit because it said "some versions of luma won't autoboot the payload starting with start_" even though the guide guarantees that the user will be on luma 7.0.5
I will note that there is a problem as it is right now: A lot of people update from ancient versions of luma to luma 7.0.5, and it asks them to reconfigure luma. People will freak out, and they will come to the discord channel …
=> Revert all recent changes to a9lh-to-b9s, and also a minor modification

_pages/en_US/a9lh-to-b9s.txt
Because we copy luma 7.0.5 to the root of the sd, renaming the payload is not needed anymore
=> Renaming the safeb9sinstaller payload is no longer needed

_pages/en_US/finalizing-setup.txt
Since it is so easy to backup otp and movable.sed there is no reason to not do it. I've seen some cases where someone may want to extract saves from a dead motherboard, and if they had essential.exefs it would be possible to do so.
=> Tell users to backup essential.exefs

_pages/en_US/installing-boot9strap-(dsiware-game-injection).txt
In the DSiWare game injection guide, during the system transfer, the user may be prompted to move the SD card from the source to the target (To move DSiWare titles). However, since the source's SD card has an already properly configured `config.bin`, moving the SD card from the source to the target will result to the target having an already properly configured `config.bin` as well. This will result in the user not booting into the Luma configuration menu on boot, and it will confuse users since the guide says "You should have booted into the Luma configuration menu"
I modified it so that the user is told to hold select on boot. This not only addresses the issue above, but it is a good test to determine whether the B9S installation went well.
=> Tweak to Section VII of DSiWare game injection

_pages/en_US/a9lh-to-b9s.txt, _pages/en_US/finalizing-setup.txt
There is really no need to have the wording "the latest fork", I've seen it twice now where people are confused as what it means. It doesn't add anything
=> Remove "latest fork" from the wording

_pages/en_US/godmode9-usage.txt, gm9_scripts/remove_extdata.gm9, gm9_scripts/remove_nnid.gm9
The success/fail messages were inverted and I also forgot to add the NNID script to GodMode9 Usage in addition to Troubleshooting.
=> Fix screwups with nnid and extdata scripts

_pages/en_US/ntrboot.txt
I figured out with the stock kernel that it does have a time bomb.
=> Update ntrboot.txt about R4I-sdhc 3ds rts

_pages/en_US/troubleshooting.txt
=> Added Clearer Instructions to the “Removing an NNID without formatting your device” section of the Troubleshooting Page  

_pages/en_US/godmode9-usage.txt
I added the GodMode9 Discord link to `/godmode9-usage`. I'm very sure that it'll look correct, but I can't be sure since I have no way of visualizing it (trying to publish it under https://sirnapkin1334.github.io/Guide_3DS/ causes it to lose CSS or something of the like). If you could visualize it to make sure that I added it correctly, that would be good.
=> Add GodMode9 Discord link

_pages/en_US/installing-boot9strap-(ntrboot).txt
Since ntrboot technically looks for start+select+x after you press power and if you hold power first and take too long it doesnt register
=> Hold power last for ntrboot

_pages/en_US/installing-boot9strap-(ntrboot).txt
Recent ntrboot_flasher versions and flashrom backups don't actually look for a file named `backup.bin` only anymore but look for a `flashcartname-backup.bin` file instead and some people think they have the wrong file
=> Be less specific about the name of backup.bin

_pages/en_US/a9lh-to-b9s.txt
This folder is only used at the end; there are 6 steps in between creating the folder and actually using it.
I propose this change for clarity (confused myself initially, on why creating a folder then start talking about /luma/payloads).
=> Moved creation of boot9strap folder at the end to avoid confusion

_pages/en_US/get-started-(old-3ds).txt
To note, Soundhax must first be updated in order to support <3.0.0.
=> Pre9otherapp supports 3.0.0 now

_pages/en_US/installing-boot9strap-(frogminer).txt
-frogtool 2.0 (srl, ctcert, private folder now bundled: effectively noob-proof, but copyrighted)
-steel diver is not dsiware
-removed ref to private folder
-updated instructions for onboard injection
-removed ref to "several services"
-added note about not spamming refresh
-i am sorry about my branch and patch fuckery
=> frogminer update

_pages/en_US/installing-boot9strap-(frogminer).txt
some systems, usually due to prior uninstallation of cfw, have a broken twl firm and cannot use frogminer. it is pointless for such users to proceed through these steps only to find they can't do it. this can be detected from stock very easily and this pr includes steps for such a test
=> update to include twl test

_pages/en_US/installing-boot9strap-(frogminer).txt
Change steelminer site to injector-only rather than another guide.
This should alleviate fractured guide confusion
This change will need to be done for all translations but most are not up to date at this point anyway and should be reworked from the current en-us translation, in my opinion.
=> change steelminer site

_pages/en_US/finalizing-setup.txt
Adds a short description of what DSP1 and `ctr-no-timeoffset` are responsible for in the *What You Need* section.
Thanks to users `ahrigatø` and `bungiefan(what does the guide say?)` from Discord, who explained what `DSP1` and `ctr-no-timeoffset` were for.
=> Add short explanations for components of the Seedminer finalization step 

_pages/en_US/finalizing-setup.txt
clarification added for screenshot. not sure removing the screenshot outright makes sense considering people get confused with too many words when pictures dont break it up.
=> note about files not being in screenshot

_pages/en_US/finalizing-setup.txt
removes potential unsafe removal and questions about "eject" vs "unmount"
=> replace GM9 eject with poweroff

_pages/en_US/finalizing-setup.txt
Should help separate the notes from the guide itself. 
hopefully this will alleviate confusion over updating Luma right after installing it.
=> add header for notes/info section

_pages/en_US/get-started.txt
This makes it more obvious to users that it is safe to update from
11.4.0+ to 11.9.0, in order to access the eShop to get a title required
for seedminer.
=> Add "Update to 11.9.0 or ..." for 11.4.0 - 11.8.0

_pages/en_US/installing-boot9strap-(fredtool).txt
exploit summary still said eshop title
now it doesn't
=> edit requirements for clarity

_pages/en_US/installing-boot9strap-(fredtool).txt
reworded the "create nintendo dsiware" to make it easier to see that it will have to be created if its not there
added some verbiage to the top of the what you need section to help remind (even after just 3 steps) that the file you need is probably on SD root
=> standardization and rewording

_data/navigation/en_US.yml
This will fix the progress tracking issue. It loops over the list of sidebar pages and then the js shows and hides them on demand.
=> Add USM Title to sidebar pages list

_pages/en_US/homebrew-launcher-(pichaxx).txt, _pages/en_US/legacy-methods.txt, _pages/en_US/seedminer.txt
Various changes have been made in this PR to aid in the transition to USM as the primary Seedminer method.
- Wording has been slightly changed when referring to other seedminer exploits, as they have been moved to the legacy methods page.
- The DS Internet Settings test has been replaced with a DSiWare management test, as the the latter is required for USM.
- "Continue to unSAFE_MODE" has been changed to "Continue to Installing boot9strap (USM)", in line with other pages on 3ds.hacks.guide.
- DS Internet and DS Download Play tests have been added to the Legacy Methods page, as well as a link to TWLFix-3DS should they be broken.
- Homebrew Launcher (Pichaxx) now links to Installing boot9strap (Frogtool), as Pichaxx + DSiWare Dumper + Fredtool is more of an edge case.
=> various changes to streamline text and reduce redundancy

_pages/en_US/get-started.txt, _pages/en_US/installing-boot9strap-(soundhax).txt, _pages/en_US/site-navigation.txt
Use `Installing boot9strap (Soundhax)` for all versions between 1.0.0 and 11.3.0, using universal-otherapp.
Changes in this PR:
get-started:
- Remove `This means that, for example, the "from 9.0.0 to 9.2.0" row includes 9.0.0, 9.1.0, and 9.2.0.` because it doesn't fit the current guide structure
- `Installing boot9strap (Soundhax)` -> from 1.0.0 to 11.3.0
installing-boot9strap-(soundhax):
- Remove USA/EUR/JPN/KOR region text ("all regions")
- Remove cart update notice
- Adjust instructions accordingly for use with universal-otherapp
site-navigation:
- Switch popular page from HBL-Soundhax to B9S-Soundhax
=> installing boot9strap (soundhax) -> 1.0.0 to 11.3.0

_pages/en_US/installing-boot9strap-(usm).txt
This page currently links to the BannerBomb3 DSiWare generator, which is incorrect for this guide. I have changed the link to point to the correct page, which is the UnSAFE_MODE DSiWare generator.
=> Fix link in "Installing boot9strap (USM)"

_pages/en_US/finalizing-setup.txt
A handful of people have been confused about how to load GodMode9 in Section VI, and have accidentally pressed the button too late or tried to time the START button, etc. The fool-proof explanation on how to load GodMode9 or the chainloader menu appears to be to press and hold START, and keep holding the START button when powering on the console.
Section VI, step 2 makes this clearer.
=> Make instruction on booting GodMode9 clearer

_pages/en_US/finalizing-setup.txt, _pages/en_US/troubleshooting.txt
updates finalizing setup page section II to link to a (new) troubleshooting section to avoid unnecessary CTRtransfers when your device fails to update
adds troubleshooting section on the troubleshooting page.
changes finalizing setup page to link to this troubleshooting section.
=> Update finalizing settup page (and add troubleshooting section) to avoid unnecessary CTR transfers on section II

_pages/en_US/get-started-(new-3ds).txt, _pages/en_US/get-started-(old-3ds).txt
Adds note to `Get Started (New 3DS)` and `Get Started (Old 3DS)` above the version table to ignore the browser version/region.
=> get-started (n3ds/o3ds): Add note about browser version/region

_pages/en_US/uninstall-cfw.txt
the "private" folder stores some data for certain apps and it may be present on a stock system, so it doesn't exactly make sense to delete it.
=> "private" exists.

_config.yml, _includes/masthead.html
looks like the guide's japanese translation is getting translations through pretty quickly.
Jpn guide is about 95% finished translating which is actually quite a bit more than some of the other languages we have up
=> add Japanese to the language list

_pages/en_US/dumping-titles-and-game-cartridges.txt
I screwed up.
In this PR:
- Dumping `.cia` guide accidentally mentions that 3DS games be dumped to `.3ds` and NDS games dumped to `.nds` etc. Message is removed
- GBA VC Backup/Restore still uses older method of identifying Title ID, so that has been changed to reflect Title manager as well.
Please provide feedback.
=> #1870 typos

_pages/en_US/finalizing-setup.txt
Fixes #1880, fixes #1871.
The GM9Megascript has the function to dump `boot9.bin` and `boot11.bin` automatically, which negates the need for going into `MEMORY VIRTUAL` manually. This should be used instead for easier dumping of said files.
The initial PR, which was since abandoned, suggests removing line 163. Personally I think it should be there, so I left it unchanged for now. Please let me know if that should be changed.
=> Use GM9Megascript to dump boot9

_pages/en_US/installing-boot9strap-(browser).txt, _pages/en_US/installing-boot9strap-(ntrboot).txt, _pages/en_US/installing-boot9strap-(soundhax).txt
After some complains from a dyslexic user, I decided to make 2 pretty minor changes
Section 3, step 1 - changed "all safety checks" to "all checks" - safeb9sinstaller just calls them "checks", so the word safety there was unneeded
Section 3, step 2 - changed "key combo given to install..." to "key combo given on the top screen to install..." - this specifically calls out where the combo will be given, to prevent users from looking at the bottom screen when the combo is on the top.
no i totally didnt forget to make this pr for like 2 weeks after making the changes shhh
=> Update installing boot9strap (browser) to more correctly reflect the on-screen information

_pages/en_US/get-started.txt
The "All versions" list in "Get Started" is redirecting to "Installing boot9strap (ntrboot)" and not "ntrboot". We can't be skipping steps here, can we?
Now it's directing to ntrboot.
=> "All versions" list is directing to wrong ntrboot page in Get Started

_pages/en_US/home.txt
This PR shortens the homepage text so that people actually read through it. The main changes are:
- Removal of most references to old CFW -- we're four years past that now.
- Removal of (technical) explanation of what boot9strap actually is -- most people don't care.
- Removal of ~~five~~ four infoboxes on this page -- honestly, there are too many. Not 100% on this change, though. My rationale is:
- The guides are barely connected these days, so linking back to hacks.guide doesn't make much sense, especially when all the guides are using different website builders.
- People with a dev unit generally already know where to go (plus, the dev guide is outdated right now anyway)
- Translate/seed could be moved to a "contribute" page. It doesn't belong on the homepage.
- Combination of many …
=> homepage v2 -- make it concise

_pages/en_US/finalizing-setup.txt
By request of @lilyuwuu `essential.exefs` is now dumped during Finalizing Setup. `.noexefs` is no more.
GM9Megascript has everything.
=> add dumping essential.exefs to finalize

_pages/en_US/bannerbomb3.txt, _pages/en_US/get-started.txt, _pages/en_US/homebrew-launcher-(pichaxx).txt, _pages/en_US/installing-boot9strap-(fredtool).txt, _pages/en_US/installing-boot9strap-(frogtool).txt, _pages/en_US/installing-boot9strap-(pichaxx).txt, _pages/en_US/installing-boot9strap-(usm).txt, _pages/en_US/seedminer.txt, _pages/en_US/site-navigation.txt
Updates guide to support 11.15. In particular:
- Removal of browserhax as main guide path -- not completely removed/stubbed yet.
- Removal of Seedminer out-of-date warning.
- Addition of Seedminer to get-started and site-nav recommended.
=> seedminer returns from the grave (11.15 guide update)

_pages/en_US/region-changing.txt
It's way too complicated and not actually useful for most people.
=> region-changing: remove link to NNID region change guide

_pages/en_US/ctrtransfer.txt, _pages/en_US/region-changing.txt
Also makes warning in region-changing consistent and moves it to the top of the page (where it is more likely to be seen). Fixes #1876.
=> ctrtransfer: add ext mem mode warning

Gemfile
This PR adds `kramdown-parser-gfm` to Gemfile. This doesn't really have anything to do with the page, but for local testing, it keeps failing to build the site without it, and it isn't really messing with the site either way, so why not? 
Admittedly this is more of an annoyance thing than anything else, but I assume other people are having this issue as well when offline testing.
=> Add kramdown-parser-gfm to Gemfile

_pages/en_US/restoring-updating-cfw.txt
This ensures that anyone who is restoring or updating CFW also copies latest luma to ctrnand to prevent errors when booting SDless, allowing the link to be used for updateluma in place of a gist.
=> restoring-cfw: add ctrnand luma

_pages/en_US/godmode9-usage.txt
Instead of launching then ejecting, just copy the NAND backup before turning on.
Instead of ejecting then reinserting, just turn off then copy out the NAND backup.
=> godmode9-usage: power off instead of eject

_pages/en_US/installing-boot9strap-(ntrboot).txt, _pages/en_US/updating-b9s.txt
Often, there are issues where the user updating boot9strap can't actually launch SafeB9SInstaller as they only have Luma3DS installed to CTRNAND. 
This should force the console to boot into SafeB9SInstaller.
There were some suggestions to download Luma 7.1 separately, but given the result would be the same either way (either it keeps rebooting to SafeB9SInstaller, or it keeps rebooting to Luma 7.1) this saves the need to download another file.
=> Updating B9S: use SafeB9SInstaller as `boot.firm`

_pages/en_US/bannerbomb3.txt, _pages/en_US/installing-boot9strap-(fredtool).txt
Minor pull request that corrects one of the instructions.
The button is labelled `Build and Download`, not `Go`.
---
The final line deletions are from the `.editorconfig` file.
```ini
insert_final_newline = false
```
* Closes https://github.com/hacks-guide/Guide_3DS/issues/1918
=> fix: correct button label on bannerbomb instructions

_pages/en_US/installing-boot9strap-(usm).txt, _pages/en_US/seedminer.txt, _pages/en_US/troubleshooting.txt
This PR:
- Switches the alternate method in Seedminer from BannerBomb3+Fredtool to USM (BannerBomb3+unSAFE_MODE)
- We may want to revisit whether one method should be explicitly recommended over the other, as both seem to be relatively equally appealing 
- Updates the Installing boot9strap (USM) page to account for the new injector site and for the new usm.bin file
- Makes BannerBomb3 (the DSiWare dumping one) an alternate on the Installing boot9strap (USM) page
- Adds barebones troubleshooting for Installing boot9strap (USM)
=> USM revival

_data/navigation/en_US.yml, _pages/en_US/get-started.txt, _pages/en_US/installing-boot9strap-(kartdlphax).txt, _pages/en_US/site-navigation.txt
As suggested by @MechanicalDragon0687. This PR:
- Adds kartdlphax instructions (based on [this gist](https://gist.github.com/lilyuwuu/adc540e700aa9d3aa0ed882ce51756b2)).
- Adds it to Get Started as a method above ntrboot (as it is more likely for someone to have a second 3DS and MK7 than a compatible DS flashcart).
While I was initially hesitant on adding it to a page other than site navigation, I feel it's a reasonable alternative to Seedminer for unminable consoles (and at the very least, it's a lot more feasible than hardmodding, where we still don't have current NFIRMs up). Just need to tweak the text on the BFM site so that it doesn't say ntrboot is the only option...
=> Kartdlphax

_includes/footer.html
The link to the privacy policy was loading the fourth title because `titles[3]` is gonna be the fourth element in the array. Since there are only three in the array and the third in `en_gb` is 'Privacy Policy', I'm gonna assume that it's meant to be `titles[2]`.
I make this mistake a lot myself.
This fixes it so that the link the the privacy policy is visible.
=> Fix privacy policy link

_pages/en_US/uninstall-cfw.txt
Fixes troubleshooting link not redirecting to the correct section after troubleshooting overhaul.
=> uninstall-cfw: fix TWLFix troubleshooting link

_pages/en_US/formatting-sd-(windows).txt
guiformat forces FAT32 on the system. This is generally okay for SDXC+ cards, but SD Card Formatter formats SD cards as according to official SD specifications, which would be much more beneficial for SD and SDHC cards. 
This automatically formats to 32KB allocation unit size, as well as formats to FAT16 for SD and FAT32 for SDHC, both of which the 3DS supports.
=> formatting-sd-win: use SD Card Formatter for 32GB and less

_pages/en_US/faq.txt
While translating, it was brought up that the South Korean modding community has practically 0 concept of what an NNID is.
This makes sense: KOR region consoles don't have such a thing.
Therefore, this is clarified.
=> faq: Clarify which regions actually have NNID

_pages/en_US/finalizing-setup.txt
This PR reworks Finalizing Setup to (hopefully) make it easier to follow. The following changes have been made:
- The explanation of "valid arm9 payloads" run as `boot.firm` has been removed, as well as references to how SysNAND CFW bypasses the need for EmuNAND.
- The Move EmuNAND infobox has been moved to right before What You Need, and more explicitly says that it doesn't apply to most people.;
- The 2.1.0 CTRTransfer warning has been removed (I don't think an N3DS will even boot on 2.1 with boot9strap, and anyone in that situation would probably ask us for help anyway)
- "What You Need" has been split into three sections, depending on what the user is downloading (CIA files, 3DSX files, and "other")
- Files are now in alphabetical order, both in What You Need and in Prep Work
- DSP1 …
=> Finalizing Setup rework

_pages/en_US/troubleshooting.txt
Description
Originally noticed by MrFaq2017 on Crowdin, four `->` arrows were missing from `troubleshooting.txt`. Simply added it to the English (source) version.
=> add missing -> to troubleshooting.txt

_data/navigation/en_US.yml, _pages/en_US/bannerbomb3-fredtool-(twn).txt, _pages/en_US/bannerbomb3.txt, _pages/en_US/seedminer.txt, _pages/en_US/site-navigation.txt, assets/js/_main.js
bb3-fred-twn: new page
bb3: add redirect for twn consoles
seedminer: add bb3-fred-twn method with clear indication and separation to show it is for twn consoles only
main.js: add bb3-fred-twn route
en_us nav: add bb3-fred-twn page
site-nav: add bb3-fred-twn page
Adding directly to guide rather than linking to gist for ease of translation. Hoping the separation and wording is clear enough that no non-TWN consoles will accidentally follow it.
May still need to be checked for 100% accuracy, but at least one person seems to have followed it without issue so far.
=> add twn seedminer method

_pages/en_US/finalizing-setup.txt
Use Luma to nullify offset and dump DSP instead of DSP1 and ctr-no-timeoffset.
=> finalizing: use luma for rtc/dsp setup

_config.yml, _includes/masthead.html
ko_KR translations have translated and proofread the main guide path:
- home
- get started
- soundhax
- seedminer
- usm (only one string left because none of us have a KOR 3DS to figure it out)
- pichaxx
- fredtool
- finalizing setup
Fredtool for TWN was left untranslated.
This should be merged after the translations PR.
=> Enable ko_KR translation

_pages/en_US/a9lh-to-b9s.txt, _pages/en_US/ctrtransfer.txt, _pages/en_US/installing-boot9strap-(hardmod).txt, _pages/en_US/installing-boot9strap-(ntrboot).txt, _pages/en_US/region-changing.txt
Added qBittorrent as torrent-client-recommendation considering Deluge hasn't got an official update for Windows or macOS in almost five years.
=> Add qBittorrent as client-recommendation

_sass/minimal-mistakes/_base.scss, _sass/minimal-mistakes/skins/_nord.scss
_Imagine using dark mode, couldn't be me_
This minor edit to the CSS will allow for better text visibility when selecting a line of text anywhere on the guide. Users of dark mode would just see white text on white highlight.
Now they see white text on... a less white highlight.
=> Manually define colours for text selection

_pages/en_US/ctrtransfer.txt, _pages/en_US/region-changing.txt
Would prefer that there is only one string to translate. They all effectively say the same thing anyway.
=> Unify all magnet link notice text

_pages/en_US/formatting-sd-(linux).txt
It's possible I missed something, but it looks like the existing instructions would have someone create a filesystem on top of the entire card instead of within the partition. This fixes that.
=> Correctness fixes for formatting MicroSD cards under Linux

_pages/en_US/a9lh-to-b9s.txt, _pages/en_US/bannerbomb3-fredtool-(twn).txt, _pages/en_US/finalizing-setup.txt, _pages/en_US/installing-boot9strap-(fredtool).txt, _pages/en_US/installing-boot9strap-(hardmod).txt, _pages/en_US/installing-boot9strap-(kartdlphax).txt, _pages/en_US/installing-boot9strap-(ntrboot).txt, _pages/en_US/installing-boot9strap-(pichaxx).txt, _pages/en_US/installing-boot9strap-(safeb9sinstaller).txt, _pages/en_US/installing-boot9strap-(soundhax).txt, _pages/en_US/installing-boot9strap-(usm).txt, _pages/en_US/restoring-updating-cfw.txt, _pages/en_US/updating-b9s.txt
This PR:
- B9S-*, AtoB, Updating-B9S: Merges the "Installing boot9strap" and "Configuring Luma3DS" sections when possible, as there is no longer anything necessary to configure in Luma3DS.
- Because B9STool can (probably) still weirdly fail to install B9S sometimes, pages that use it (B9S-Fredtool and BB3-Fredtool-TWN) now have a "Luma3DS Verification" section that prompts people to check for the existence of the `luma` folder and `config.ini`. The next section has people do things on SD anyway, so it works out pretty well.
- B9S-*, AtoB, Updating-B9S: Rewords/clarifies the check for people who can't t boot because of missing `boot.firm`. (Not necessarily related to Luma 11, but useful for clarification purposes as we currently link to a pretty long troubleshooting page).
- …
=> Guide update for Luma3DS v11.0

Gemfile, _config.yml
Adds the [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) plugin, which allows pages to be redirected.
=> add redirect plugin

_pages/en_US/bannerbomb3-fredtool-(twn).txt, _pages/en_US/faq.txt, _pages/en_US/get-started.txt, _pages/en_US/home.txt, _pages/en_US/installing-boot9strap-(fredtool).txt, _pages/en_US/installing-boot9strap-(kartdlphax).txt, _pages/en_US/installing-boot9strap-(pichaxx).txt, _pages/en_US/installing-boot9strap-(usm).txt, _pages/en_US/seedminer.txt
Updates guide for 11.16.
- Pages that require 11.16 and use universal-otherapp have been removed from the main guide path but still exist, with notices on the top in case of direct links.
- Pages that use b9stool (BB3+Fredtool/TWN) have been removed from the main guide path but still exist, with notices in case of direct links.
- unSAFE_MODE is the one and only recommended Seedminer method for now, with no changes required for 11.16.
- Notices for 11.16 added/updated on homepage and FAQ.
=> Update guide for 11.16

_pages/en_US/installing-boot9strap-(hbl-usm).txt, _pages/en_US/installing-boot9strap-(usm).txt
- Make it clear you need to keep holding while turning console on.
- Direct people to the above warning on broken buttons if this is suspected to be the cause of SAFE_MODE boot fail.
- Partially revert https://github.com/lifehackerhansol/Guide_3DS/commit/01edecf0ac5e05018e71ff11022883ba6aecae41
to bring button red warning back on top of page.
Thank you kind stranger for guide feedback.
=> *usm: clarify SAFE_MODE boot instructions

_pages/en_US/bannerbomb3.txt
"I am in the hardware safe mode testing thing rn it prompted an update and after I pressed cancel it didn't go to the home menu it just shut off is this fine?"
"in this section of the guide my 3ds does go into the system update menu but doesn't go back to the main menu after I press the cancel button should I still do the safe mode method or the other one ?"
should fix these questions
=> clarify hardware button check

_pages/en_US/a9lh-to-b9s.txt, _pages/en_US/checking-for-cfw.txt, _pages/en_US/faq.txt, _pages/en_US/finalizing-setup.txt, _pages/en_US/installing-boot9strap-(fredtool).txt, _pages/en_US/installing-boot9strap-(usm).txt, _pages/en_US/move-emunand.txt, _pages/en_US/seedminer.txt, _pages/en_US/troubleshooting.txt, _pages/en_US/uninstall-cfw.txt
- Convert FAQ and Troubleshooting pages to clickable collapsibles to improve readability.
- Add separate table of contents to Troubleshooting (for mobile users)
- Remove a couple of irrelevant troubleshooting
- Update pages that link to troubleshooting to use new headers
=> faq+troubleshooting: collapsibles

_pages/en_US/ctrtransfer.txt
fix missing step
because the step is missing and people cant infer
=> FBI->SD not FBI->gm9

_pages/en_US/troubleshooting.txt
If b9stool 7 was run and luma config did not boot, something unexpected and weird is going on. The old tactic of dry updating will not help, and manual assistance will be necessary to find a fix specific to what unexpected firm was installed.
Please wait to merge this until the new b9stool changes have been released. Also, I'm bad at wording things so if anyone wishes to reword this please do.
=> update troubleshooting for new b9stool

_pages/en_US/troubleshooting.txt
safecerthax :O 
proxy works with safecerthax and consoles cartupdating from versions vulnerable to soundhax can still use soundhax together with universal otherapp. (unless 11.16 but then they wouldnt be doing ssloth)
=> add troubleshooting for cartupdated consoles

_includes/consoleVersionSelect.html, _pages/en_US/get-started.txt
This time, it's an HTML include, and not a relative include
This way changing the HTML tags like what happened the last time we edited this doesn't break all translations for the 400th time
Fixes #2225
=> Move version selector to its own include

_pages/en_US/ctrtransfer.txt, _pages/en_US/finalizing-setup.txt, _pages/en_US/godmode9-usage.txt, _pages/en_US/include/ctrtransfer-cleanup.txt, _pages/en_US/include/ctrtransfer-main.txt, _pages/en_US/include/ctrtransfer-prep.txt, _pages/en_US/include/ctrtransfer-ticket-copy.txt, _pages/en_US/include/format-sd-gm9.txt, _pages/en_US/include/launch-hbl-dlp.txt, _pages/en_US/include/nand-backup.txt, _pages/en_US/move-emunand.txt, _pages/en_US/region-changing.txt
Pages using the CTRTransfer sections:
- ctrtransfer
- region-changing
Pages using the NAND backup section:
- godmode9-usage
- region-changing
Pages using GM9 SD format section:
- godmode9-usage
- move-emunand
Pages using the HBL launch via DLP section:
- finalizing-setup
- installing-boot9strap-(hbl-usm)
=> Add includes for ctrtransfer steps

_pages/en_US/ctrtransfer.txt, _pages/en_US/include/ctrnand-datayeet.txt, _pages/en_US/include/ctrtransfer-cleanup.txt, _pages/en_US/region-changing.txt
- Reword several introductory parts, including more specific information (i.e. when a region change should be performed, what exactly a region change 'breaks')
- Switch from system format notice to mandatory ~~system save data~~ cfgsave removal (this is to prevent issues on o3ds while also being less destructive in such cases, hopefully - also, since these are consoles that are likely to be imported, it is unlikely for a significant amount of system data to be important to the user)
- Add success notice on bottom (cosmetic)
- Merge sections VI and VII (section VI also takes place in godmode9, making VII redundant)
~~Pending discovery of root cause of extended memory mode and exiting friends list / game notes breaking. If the cause is found and easy to implement (i.e. deleting a single …
=> region-changing: data yeet, reword

.github/workflows/publish.yml
This allows us to use Jekyll v4, by separately building the website and pushing it to `gh-pages` branch.
This requires GitHub Pages to point to `gh-pages` branch. 
This is currently untested, and is really only here if we ever need some feature in Jekyll v4 that GH Pages's v3 doesn't offer (or more accurately, when I eventually _snap._)
=> Add GitHub Actions build script to bump Jekyll to v4

assets/js/selecting.js
both surprised and not, very specific version of old 3ds kor(/twn/chn) browser, 1.7630/v10240, should be shipped with 11.1~11.8, isn't supported by browserhax. weird gap here, but [it simply exist](https://github.com/zoogie/web/blob/master/nbhax/index.html#L68-L73).
probably will never notice this without [existing case](https://discord.com/channels/196618637950451712/247557068490276864/1108600147878887475)
=> fix wrong redirection for unsupported kor ssloth-browser

_pages/en_US/include/install-boot9strap-safeb9sinstaller.txt
The troubleshooting link for Installing boot9strap (USM): Section IV has a typo and is broken
=> Fix SafeB9SInstaller troubleshooting link

_pages/en_US/homebrew-launcher-(smilehax-iie).txt
Yeah, why we need movable.sed to dump movable.sed
=> Fix wrong movable.sed requirement for smilehax-iie

_pages/en_US/troubleshooting.txt
This is unnecessary as, if the user used the version selector, they shouldn't be on a cartupdate.
=> troubleshooting: remove redundant SSLoth-Browser cartupdate steps

_pages/en_US/installing-boot9strap-(kartdlphax).txt
This pull request adds a piece of information that might be very helpful for some people trying to get CFW on updated consoles: the source 3DS can be region-changed to match the target 3DS. 
kartdlphax requires two consoles on the same region, but nowhere does the documentation state whether region changed consoles work as the source 3DS; after a desperation move by myself today to get two JPN old 3DS LL on 11.17.0 running CFW, i can confirm it works even if the source 3DS wasn't originally the same region, as I did it using a region-changed EUR old 3DS. 
This info might be very helpful for people in the same situation as me, that have consoles from different regions and don't want to buy a flashcart.
=> Add some more info on kartdlphax

_pages/en_US/troubleshooting.txt
As per suggestion that a less-tech-inclined user could potentially be looking in the wrong place.
=> troubleshooting: move universal-otherapp SB9SI error to "Issues with SafeB9SInstaller"

_pages/en_US/faq.txt
Digital game and save data loss is a common fear, so I believe it should be added to the pre-installation FAQ. This commit adds back a sentence that used to be on the home page that I believe was first written by lilyuwuu in pull #1888, then removed by the same person in commit 93b4f3b.
=> Add question about digital game and save data loss to FAQ

_pages/en_US/bannerbomb3-fredtool-(twn).txt, _pages/en_US/include/exploit-flipnote.txt, _pages/en_US/include/install-boot9strap-b9stool.txt, _pages/en_US/installing-boot9strap-(fredtool-inject).txt
This commit splits the rather large Flipnote exploit section into the following includes:
- exploit-flipnote
- install-boot9strap-b9stool
This also rewords portions of the Fredtool steps in individual pages so that the steps to launch Flipnote Studio are now in the Flipnote Exploit section, so as to make the b9stool section flow through easily.
This also allows to remove more arguments within the `include_relative` directive.
=> fredtool*: split Flipnote steps and b9stool steps, move things around to align

_pages/en_US/installing-boot9strap-(fredtool-inject).txt
Looks to be a remnant from when we did BannerBomb3 -> Fredtool, but since we no longer do that, the F00D43D5.bin shouldn't be there.
=> Remove F00D43D5.bin line

_pages/en_US/bannerbomb3-fredtool-(twn).txt, _pages/en_US/installing-boot9strap-(kartdlphax).txt, _pages/en_US/installing-boot9strap-(kartminer7).txt, _pages/en_US/installing-boot9strap-(menuhax).txt, _pages/en_US/installing-boot9strap-(ssloth-browser).txt
This PR applies the change made in https://github.com/hacks-guide/Guide_3DS/commit/ddb273fedfb14da3ba5cb9cfb86ca6ca53863aca to the menuhax-based and SSLoth pages (to try to lessen the people skipping steps and for consistency with MSET9)
~~this also adds the notice to bb3 twn in the first place since it seemed to be missing, though I don't know how important this is in the first place~~
=> Move the Luma3ds installed notice to after any post-install non-finalizing steps.

_pages/en_US/installing-boot9strap-(super-skaterhax).txt
yeah this is my fault, but all versions that we direct skater to goes to mset9 on old 3ds, so its just easier for the user to have a direct link and not risk them messing up the input this time
=> 11.16 and 11.17 Old 3DS both go to MSET9 anyways

_pages/en_US/troubleshooting.txt
This updates the troubleshooting for Error #18 of Finalizing Setup to send you to the removing MSET9 section for both the CLI method and the Play Store method, rather than just sending you to the landing page of MSET9.
The finalize script should be updated as well to include a new tinyurl link for both methods.
=> mset error #19 -> mset-cli/mset-play-store

_pages/en_US/troubleshooting.txt
While Nintendo 3DS is probably the folder they'll end up putting it in (many people confuse that with the root), there are other folders that the script can detect. They really don't need to know where they misplaced it, just that they did, and they should enter the keycombo to fix it.
=> Remove reference to Nintendo 3DS for finalize.romfs placement.

_pages/en_US/installing-boot9strap-(mset9-cli).txt, _pages/en_US/installing-boot9strap-(mset9-play-store).txt
To make things simpler and confuse users less, have users eject on page one without going hunting for mii maker, if mii maker is missing they will need to do Fresh anyway
This avoids people pressing buttons which can lead to a crash regardless
=> Changes to Section 2 Step 5 for MSET9

_pages/en_US/a9lh-to-b9s.txt, _pages/en_US/faq.txt, _pages/en_US/finalizing-setup.txt, _pages/en_US/home.txt, _pages/en_US/include/3ds-11.17.txt, _pages/en_US/include/3ds-online.txt, _pages/en_US/key-information.txt, _pages/en_US/region-changing.txt, _pages/en_US/updating-b9s.txt
Do not merge until online services have shut down and it is confirmed that no 3DS update has been released!
- A9LH-to-B9S and Updating B9S: Remove reference to online play (should have done this long ago but I guess we forgor)
- FAQ: Remove reference to CFW working with online play (which no longer exists); keep message about bans in case people still ask
- Homepage, keyinfo, faq: swap out 3ds-11.17 (now gone, it's been almost a year) with 3ds-online
- Key-info: Adjust risks warning to remove reference to online play
- Region changing: Swap out reasoning for game updates
- Finalizing Setup: remove reference to Pretendo network dumps / SpotPass Archive
=> update guide for end of online play

_pages/en_US/dumping-titles-and-game-cartridges.txt
GBA VC Saves are backed up to 0:/gm9/out, not 0:/gm9
=> Correct GBA VC save path

_pages/en_US/installing-boot9strap-(mset9-cli).txt
The name of the zip has been changed to MSET9-v2.0.zip, no longer Release
=> MSET9-CLI: Change zip name

docs/_include/ctrtransfer-main.md, docs/_include/ctrtransfer-prep.md, docs/ctrtransfer.md, docs/region-changing.md
this pr aims to simplify the ctrtransfer (and region changing) process by doing the following:
- move to a script based tutorial
- merge ctrtransfer ticket copy into said script
- make dirty flashes (flashing without verifying sha hash) impossible by verifying with the script
- make flashing incompatible nands impossible (n3ds nand on o3ds) with the script
- prompting the user if essential console info (such as secinfo) is broken in any way, aborting the transfer (thanks starlit)
=> CTRTransfer guide makeover

docs/public/assets/js/link-common.js, docs/public/assets/js/soundhax-frankenfirm-link.js, docs/troubleshooting-soundhax.md
first, ref: https://gist.github.com/danny8376/524394a41202c3617e6a1ef6c181fa91
the site should cover all cases include 2.1.0 handling, hopefully
[js part of the site](https://github.com/nedwill/soundhax/compare/master...danny8376:soundhax:frankenfirmware#diff-4d6443d6dc5d62f22ddb20623fe3686e9df0b374acbfed8fe67e8feba447f911)
and this should resolve #2279
i don't think there's a good way to determine which sound app version they have without running normal soundhax first, even though it's almost guaranteed to fail (for 5.0.0 and greater)
=> Add frankenfirm soundhax to troubleshooting

docs/_internal/consoleVersionSelect.html, docs/public/assets/js/common.js
This avoids users mindlessly clicking to a potentially invalid page.
Also fixes a bug where the version is marked as valid when empty...
=> consoleVersionSelect: add dummy value as first option

docs/installing-boot9strap-(mset9-cli).md
The version of Python from the Microsoft Store does not work with MSET9, in part because this version doesn't include the "py" launcher, which is what MSET9-Windows.bat wants. I don't know if it does actually work if mset9.py is used directly though, but until then, the python.org installers should be recommended.
=> installing-boot9strap-(mset9-cli): recommend against Microsoft Store

docs/a9lh-to-b9s.md
Explicitly clarify that the contents of the latest Luma3DS ZIP should be extracted in Step 3 of Section 1 of the AtoB guide.
In the AtoB guide (`a9lh-to-b9s.md`), "What You Need" has you download two Luma3DS versions - v7.0.5 (last version compatible with a9lh), and the latest version.
However, in the following section (Prep Work), step 3 is worded ambiguously, and does not clarify which Luma3DS version should be used:
> 3. Copy everything from Luma3DS `.zip` to the root of your SD card
This PR rewords Step 3 to explicitly clarify that the latest Luma3DS ZIP should be used:
> 3. Copy everything from the latest Luma3DS `.zip` to the root of your SD card
=> Clarify Luma3DS versions in AtoB guide

docs/installing-boot9strap-(ssloth-browser).md
* use error code instead of cert warning text
* reword a bit since we'll always get certificate error now
* proper indentation to fix broken ordered list
Should the certificate error be moved into an separate step?
Feel not really ideal since it'll be separated by the warning prompt.
=> Fix and tewaks for ssloth

docs/installing-boot9strap-(super-skaterhax).md, docs/public/assets/js/selecting.js
Skaterhax does actually work properly with the modified SSL cert, despite initially thinking it doesn't.
This PR does the following:
- Reverts skaterhax stub/warning (goodbye jumpscare pony, gone but not forgotten)
- `distraction.gif` kept for now... possible reuse on uninstall-cfw? ;)
- Updates skaterhax link to `https://skater.686178.xyz/go/super` (`/korea` for KOR, untested)
- Rewrites skaterhax instructions to be as follows:
- Reset browser data (closes browser)
- Enter URL manually
- Bookmark page
- Delete cookies
- Close browser
- Reopen browser
- If fail, change language (implicit reboot) and try this sequence of instructions again
- Rewords in-line troubleshooting a bit
- Adds a 'helpful' video guide describing how to skaterhax
- Might rework this video to add text steps / circle …
=> reimplement skaterhax

docs/_internal/consoleVersionSelect.html, docs/get-started.md, docs/public/assets/js/selecting.js
If they don't select "Ver.", they have Luma3DS and have skipped the CFW check.
Hopefully, I didn't screw up any translations with my "otherPrefix" thing. Also, I wasn't 100% sure what to call the Ver/Sys/Emu/etc. thing, I think version prefix makes sense though.
=> consoleVersionSelect: add version prefix

.github/workflows/crowdin-commit.yml
This does the following:
- If a push to main branch was successful, contents will be synced to Crowdin. This allows automation of syncing source text, making it less of a hassle to synchronize all translations.
- Bi-weekly, translations will be polled from Crowdin. A build test will run to make sure that the site will compile, and finally, it will be pushed to the main branch. This saves the effort of manually syncing translations.
=> Add Crowdin automation scripts

docs/dumping-titles-and-game-cartridges.md
Be more consistent with what is said on the "Key Information" page and what is used in several places on the dumping guide page as well
=> Switch to angle brackets

docs/troubleshooting-ssloth-browser.md
This PR adds information about how to fix possible green screen crashes when executing ssloth browserhax. I just had this happen when hacking my o3dsxl and found a few other occurrences when searching through the Nintendo Homebrew assistance channels and thought this would be a good addition to the docs. Resetting the browser save data fixes it.
=> ssloth-browser: add instructions for green screen crash

docs/a9lh-to-b9s.md, docs/godmode9-usage.md, docs/installing-boot9strap-(mset9-cli).md, docs/installing-boot9strap-(mset9-play-store).md, docs/installing-boot9strap-(super-skaterhax).md, docs/restoring-updating-cfw.md
changed wording about replacing files on a couple of pages as the current wording is confusing to some. changed wording to "If any of the files exist, overwrite them with the new files" from "overwrite any existing files"
=> Fix confusing wording about replacing the existing files

docs/f3-(linux).md
The latest `f3` version for linux is `v9.0`.
This change could be alternatively done as `releases/tag/v9.0` instead, but I've noticed pages for other sd card checking tools already use `releases/latest` so I've decided to use this here too for consistency.
=> Fix the outdated f3 releases link
