_pages/DSiWare-Downgrade.md
Warnings about using the minimal transfer option "Low-Capacity microSD Card Transfer" from an old source system to a new3ds target system. Documentation below. Closes https://github.com/Plailect/Guide/issues/738 
http://au.ign.com/wikis/nintendo-3ds/3DS_to_New_3DS_or_3DS_XL_System_Transfer
https://www.youtube.com/watch?v=Y88G3tp_f88
=> Updates for 2DS/O3DS to N3DS transfer

_pages/Homebrew-Launcher-(Browser).md
Replaced the 
> 1.See [this](https://github.com/Plailect/Guide/issues/684)
on section III for whats inside "this".
=> Transcript of the "this" website on Section III (Homebrew-Launcher-(Browser).md)

_pages/DSiWare-Downgrade.md
Same typo as last one, except I didn't realize it appears twice in this page.
=> Fixed typo on line 117 "SYSNAND TWLN"

_pages/Installing-arm9loaderhax.md
=> Fix link typo

_pages/DSiWare-Downgrade-(Save-Injection).md
I assume this was meant to read 11.1.0.
=> waithax doesn't work on 11.2.0

_pages/2.1.0-ctrtransfer.md
I've seen a few people end up with this now and complain that the guide makes no mention of it. I assumed it'd be common sense, but oh well. I didn't even know it was possible to get this far with it. I've never bothered using it myself though.
=> Add note about microSD management

_pages/Installing-arm9loaderhax.md
A recent change in the restoring system steps made the old message incorrect.
=> Correct EmuNAND notice

_pages/en_US/DSiWare-Downgrade-(App-Injection-and-Second-3DS).md
=> Release, not commit, I guess.

_pages/en_US/Updating-A9LH.txt
It should have this name, because step 6 in Section I
=> down_safea9lhinstaller.bin

_pages/en_US/Get-Started-(New-3DS).txt, _pages/en_US/Get-Started-(Old-3DS).txt
Not safe, by now. As suggested on translation group.
=> Remove update notice from Get Started

_pages/en_US/9.2.0-ctrtransfer.txt, _pages/en_US/Installing-arm9loaderhax.txt, _pages/en_US/Move-EmuNAND.txt, _pages/en_US/Region-Changing.txt, _pages/en_US/Updating-A9LH.txt
=> Remove 'rename GodMode9.bin to GodMode9.bin'

_pages/en_US/finalizing-setup.txt
Most people will likely not need to use this again and will free space by deleting it.
=> Self-Delete DSP1

_pages/en_US/installing-boot9strap-(2xrsa).txt
The phrase indicates like there are several urls but there's only one
=> Typo on 2xrsa

_pages/en_US/installing-boot9strap-(homebrew-launcher).txt
=> Remove unneeded reference to magnet links

_pages/en_US/installing-boot9strap-(dsiware-game-injection).txt, _pages/en_US/installing-boot9strap-(dsiware-save-injection).txt, _pages/en_US/troubleshooting.txt
The added dsiware troubleshooting steps are already referenced in the guide, but missing from the troubleshooting page.
=> Various improvements to the DSiWare Injection guide

_pages/en_US/faq.txt, _pages/en_US/godmode9-usage.txt, _pages/en_US/region-changing.txt, _pages/en_US/troubleshooting.txt, _pages/en_US/updating-b9s.txt
Various grammar, syntax, and punctuation fixes for clarity.
=> Grammar fix

_pages/en_US/flashing-ntrboot-(3ds-single-system).txt
The following paragraph goes on to describe which flash carts are compatible, then the rest talks about "do this and that" with your flash cart.  So saying you need "nothing more than your stock unhacked 3DS" isn't quite right.
=> Clarify the requirements.

_pages/en_US/godmode9-usage.txt
addressing #1311, shameless copy paste.
=> Update Godmode9 Usage to address issue #1311

_pages/en_US/home.txt
It's a very tempting but misleading button/link
=> Remove unnecessary confusion for 11.4+ users (soundhax)

_pages/en_US/uninstall-cfw.txt
=> Checkpoint instead jksm

_pages/en_US/a9lh-to-b9s.txt, _pages/en_US/get-started.txt, _pages/en_US/homebrew-launcher-(alternatives).txt, _pages/en_US/homebrew-launcher-(soundhax).txt
* Fix #1411 
* Fix #1412 
* Fix #1413 
* Fix #1414 
* Fix that the subheading "Version Table" is before the banwave message instead of after like it should be
=> Several fixes

_pages/en_US/a9lh-to-b9s.txt
Fixed this:
Also did a few small tweaks as well
=> Small tweaks to a9lh-to-b9s

_pages/en_US/troubleshooting.txt
It no longer uses H&S injection
=> Remove references to finalizing-setup

_pages/en_US/a9lh-to-b9s.txt, _pages/en_US/finalizing-setup.txt
Minor tweaks to Section VII
Also modified both a9lh-to-b9s.txt and finalizing-setup.txt to match them up
=> Section VII tweaks

_pages/en_US/troubleshooting.txt, gm9_scripts/remove_extdata.gm9, gm9_scripts/remove_nnid.gm9
=> Use a GodMode9 script to automate the NNID removal and extdata removal troubleshooting sections

_pages/en_US/homebrew-launcher-(soundhax).txt
This brings the page in line with changes introduced in 92069ae.
=> update instructions for when a red screen is encountered

_pages/en_US/installing-boot9strap-(dsiware).txt
I also placed the method first in the list, as it is quite painful to see people read "You need a hacked 3DS" and quit instantly.
=> Add explanation for Seedminer

_pages/en_US/flashing-ntrboot-(3ds-single-system).txt
Both say the same thing, only one links to the chart.
=> Remove duplicate sentence

_pages/en_US/installing-boot9strap-(frogminer).txt
=> Fix spelling error in frogminer guide

_pages/en_US/installing-boot9strap-(seedminer).txt
=> Small Grammar Change

_data/navigation/en_US.yml, _pages/en_US/get-started.txt, _pages/en_US/homebrew-launcher-(steelminer).txt, _pages/en_US/installing-boot9strap-(frogminer).txt
First time, go easy ;)
Split the frogminer guide into multiple files, en_US only.
Let me know what mistakes i made as far as grammar, style, or anything else that seems off.
=> split frogminer into steelminer+frogminer

_pages/en_US/finalizing-setup.txt
Guide says to copy it, but it's not in the previous step.
=> .bin.sha added

_pages/en_US/finalizing-setup.txt
Didn't add the ` on the end which made that step have weird markdown.
~~silly me~~
=> Fixed my mistake on adding .bin.sha

_pages/en_US/seedminer.txt
=> remove erroneous consonant

_pages/en_US/seedminer.txt
seen an awful lot of confusion related to this
also changed the wording slightly in line with currency updates
=> change bfm instructions for clarity

_pages/en_US/homebrew-launcher-(steelhax).txt
jisagi's is down and updated link to use the new alternative.
=> Now Points to bfm's save injector

_pages/en_US/uninstall-cfw.txt
add extra depth to uninstall instructions incl a safety check for brickability
also add deleting cfw apps to avoid permacrashing data management
=> comprehensive uninstall instructions

_pages/en_US/finalizing-setup.txt
sharkive was intentionally broken and there are no plans to fix it
removing it from the guide
=> remove sharkive

_pages/en_US/finalizing-setup.txt
Reverts hacks-guide/Guide_3DS#1674
=> Revert "remove sharkive"

_pages/en_US/seedminer.txt
i have been seeing an awful lot of users lately who are very confused about the whole "this method requires a powerful pc". it gives them the impression that *they* need the powerful pc. i've edited the line to suggest more heavily that someone else can do it for them and to just continue on
=> alter graphics card line

_pages/en_US/installing-boot9strap-(fredtool).txt, _pages/en_US/installing-boot9strap-(frogtool).txt
people are getting confused about b9stool and what is actually meant to happen
=> b9s clarity

_pages/en_US/homebrew-launcher-(steelhax).txt
=> Steel Diver instead of Steel Divers

_pages/en_US/homebrew-launcher-(alternatives).txt
add compatibility statement at the top of page to resolve #1687
=> add compatible versions

_pages/en_US/homebrew-launcher-(steelhax).txt
Smealum's site currently isn't updated for the 11.10 otherapp payloads
=> temporarily use DeadPhoenix's fork of smealum's site for steelhax

_pages/en_US/homebrew-launcher-(steelhax).txt
Asked VegaRoXas for permission to rehost as zip with only steelhax folder. 
permission granted. 
modification should make it less error prone for users copying files
=> change steelhax to rehost of zip

_data/navigation/en_US.yml, _pages/en_US/bannerbomb3.txt, _pages/en_US/dsidumper.txt, _pages/en_US/finalizing-setup.txt, _pages/en_US/homebrew-launcher-(steelhax).txt, _pages/en_US/installing-boot9strap-(fredtool).txt, _pages/en_US/seedminer.txt, _pages/en_US/site-navigation.txt
adds the newest exploit to the chain
standardizes all current users to seedminer->multiple options->fredtool->finalizing setup
deprecates frogtool
#1699
=> Updating guide for bannerbomb3

_pages/en_US/bannerbomb3.txt, _pages/en_US/dsidumper.txt
add some clarifying points to the guide about which dsiware backup to use
=> Mechanical dragon0687 bb3 clarity

_pages/en_US/installing-boot9strap-(fredtool).txt
Movable doesn't actually need to be on your SD card for this
=> Movable.sed not on sd

_pages/en_US/get-started.txt
there was an nfirm update, but b9stool has been updated and everything else is confirmed to work fine
=> update version table for 11.12

_pages/en_US/get-started.txt, _pages/en_US/home.txt
=> update to 11.13

_pages/en_US/finalizing-setup.txt
Sharkhive no longer works, Checkpoint is used for cheats now.
=> Update Cheats on finalizing

_pages/en_US/installing-boot9strap-(soundhax).txt
installing b9s (soundhax) now supports 2.1/2.2
=> small text change for installing-boot9strap-(soundhax)

_pages/en_US/finalizing-setup.txt, _pages/en_US/installing-boot9strap-(usm).txt, _pages/en_US/legacy-methods.txt, _pages/en_US/seedminer.txt, _pages/en_US/site-navigation.txt
yes, another one. with props to zoog and deadphoenix
this makes usm the primary method, deprecating fredtool and other flipnote based exploits
the only issue users may have is twl titles from a previous cfw uninstall which can be fixed with twlfix
i will be requesting reviews of this
=> introduce new method

_pages/en_US/installing-boot9strap-(usm).txt
Too many people are skipping to the next section. I think the wording could be a bit better, so feel free to make any changes.
=> Add warning for if the screen does not flash red (usm)

_pages/en_US/get-started.txt
=> Remove "Browser" & "No Browser"

_pages/en_US/a9lh-to-b9s.txt, _pages/en_US/updating-b9s.txt
They were already updated in get started, but we never updated them here.
=> Update ban prevention steps in atob and update b9s

.github/ISSUE_TEMPLATE/console-issue.md, .github/ISSUE_TEMPLATE/guide-issue.md, .github/pull_request_template.md
This will help users format their issuers and collaborators give context to their contribution
=> Add issue and pull request templates

_pages/en_US/formatting-sd-(windows).txt
This adds a guide to format the SD card. First one is for Windows only, ones for Linux and Mac will come after this one receives some polish.
This needs things like warnings (e.g. "This will erase everything!") but I don't know of the best place to put them.
=> Formatting SD guide (Windows)

_pages/en_US/formatting-sd-(mac).txt
Unfinished, needs steps for Yosemite/10.10 and before.
=> Formatting SD guide (Mac)

_pages/en_US/region-changing.txt
please look at this closely i'm sure i made a mistake somewhere
=> Update region changing guide to add nand backup and update eshop warning

_pages/en_US/installing-boot9strap-(safecerthax).txt, _pages/en_US/installing-boot9strap-(ssloth-browser).txt
=> Mention that the 3DS adds preceding zeroes on the DNS

_pages/en_US/installing-boot9strap-(ntrboot).txt
yes we got a complaint about this, im not a fan of "3DS's" either but it's the best we can do unless someone has a better idea
=> reword installing boo9strap to say its the 3ds's sd

_pages/en_US/finalizing-setup.txt
Every other console has a hb app store, lets add one to 3ds too
Adds Universal Updater to the finalizing setup page for 3DS
=> add universal updater to the finalizing setup

_pages/en_US/finalizing-setup.txt
=> dont forget the dash in universal - updater

_data/navigation/en_US.yml, assets/js/_main.js
makes a common path for routes and then allows custom paths for models to replace or add to that
removes old routes for pages that dont exist
fixes current routing for existing pages
=> add notes on routing and general cleanup

_pages/en_US/godmode9-usage.txt
=> Update GM9 Discord Link

_pages/en_US/installing-boot9strap-(browser).txt
=> fix typo in installing boot9strap browser

_pages/en_US/home.txt
This seems to be a common enough issue that adding this statement should address this
=> Add requirement to be able to add files to the SD

_pages/en_US/checking-for-cfw.txt, _pages/en_US/home.txt, _pages/en_US/restoring-updating-cfw.txt, _pages/en_US/site-navigation.txt
This PR:
- adds a note on the latest system version and whether it is safe to update
- renamed Restoring CFW to Restoring/Updating CFW
There are a lot more that could be added, such as it becoming a landing page in case some people have A9LH for some reason or something like that. A tool for checking b9s version would be nice. As this is more preliminary or anything, I would rather this page go through some reviewing before merge.
If you have suggestions ping me on Discord, comment here, or just directly commit.
=> Add note on updating system and CFW

_pages/en_US/installing-boot9strap-(pichaxx).txt
Title says it all. Recommendation by @MechanicalDragon0687.
=> b9s-pichaxx: add QR to eShop page

_pages/en_US/troubleshooting.txt
This renders to make it look less weird.
Really not much to say about it. I just did +1 to all the headers and removed a few lines.
=> troubleshooting: change heading numbers

_pages/en_US/get-started.txt
People don't read and just click the first whatever link, so let's put the latest version first.
=> get-started: flip version table

_sass/minimal-mistakes/_notices.scss, _sass/minimal-mistakes/_tables.scss
Links look like ass right now as of the rebase, this makes it more like the old guide we had. 
Am willing to take opinions.
=> Use some better colouring on links in notices, also fix table borders

_config.yml, _includes/masthead.html
nl_NL translations have translated and proofread the main guide path:
- home 
- get started
- soundhax 
- seedminer
- usm 
- pichaxx 
- fredtool 
- finalizing setup
This should be merged after the translations PR.
=> Enable nl_NL translation

_sass/minimal-mistakes/_page.scss
=> Add user-select: None to header-link

_pages/en_US/faq.txt
=> faq: replace question hyperlinks with headers

_pages/en_US/troubleshooting.txt
=> troubleshooting: fix #2011

_pages/en_US/installing-boot9strap-(usm).txt
None of this is tested. I just took zoogie's words at face value lol
USM 1.3 will reboot to SafeB9SInstaller. So relevant instructions were copy-pasted.
=> usm: update for USM 1.3

_pages/en_US/installing-boot9strap-(usm).txt
Reverts hacks-guide/Guide_3DS#2020 due to bug.
=> Revert "usm: update for USM 1.3"

_pages/en_US/installing-boot9strap-(usm).txt
Reverts hacks-guide/Guide_3DS#2021 (bug appears to be fixed, still need to update it on injector side but can't do anything about that right now)
=> Revert "Revert "usm: update for USM 1.3""

_pages/en_US/faq.txt, _pages/en_US/home.txt
=> Drop BootNTR warning for 11.16

_pages/en_US/checking-for-cfw.txt
=> verbs are important

_pages/en_US/get-started.txt
=> Nintendo literally did a derp fix

_pages/en_US/get-started.txt, _pages/en_US/installing-boot9strap-(kartdlphax).txt
kinda tested, last 2 sections untested, should work though
i hope this is not already internally denied
=> bring back kartdlphax

_pages/en_US/bannerbomb3-fredtool-(twn).txt, _pages/en_US/installing-boot9strap-(fredtool).txt
Switch from old injector to Jenkins injector (I dub thee the Jankins injector)
mostly copypaste from TWN version but use DS Internet instead
=> [DNM] fredtool: switch from nhnarwhal injector to nelthorya injector

_pages/en_US/bannerbomb3.txt, _pages/en_US/installing-boot9strap-(fredtool).txt, _pages/en_US/installing-boot9strap-(usm).txt, _pages/en_US/seedminer.txt, _pages/en_US/troubleshooting.txt
and it improves the guide as a whole. looks awful currently
=> move to using bb3 multihax

_pages/en_US/installing-boot9strap-(fredtool).txt, _pages/en_US/installing-boot9strap-(usm).txt, _pages/en_US/troubleshooting.txt
saves space and adds more troubleshooting
=> improve troubleshooting

_pages/en_US/home.txt
yes(this sentence should really get removed)
=> It's actually not really easy to hack your 3DS. Not everyone can do it.

_pages/en_US/homebrew-launcher-(pichaxx).txt, _pages/en_US/troubleshooting.txt
migrate references to pichaxx to new injector page
=> migrate references to pichaxx to new injector page

_pages/en_US/troubleshooting.txt
thanks to luigoalma for mentioning this fix
=> create troubleshooting for jp n3ds error 032-0420

_pages/en_US/installing-boot9strap-(ssloth-browser).txt, _pages/en_US/troubleshooting.txt
=> yet another try to make ssloth better

_pages/en_US/a9lh-to-b9s.txt, _pages/en_US/installing-boot9strap-(hardmod).txt, _pages/en_US/installing-boot9strap-(hbl-usm).txt, _pages/en_US/installing-boot9strap-(kartdlphax).txt, _pages/en_US/installing-boot9strap-(ntrboot).txt, _pages/en_US/installing-boot9strap-(soundhax).txt, _pages/en_US/installing-boot9strap-(usm).txt, _pages/en_US/updating-b9s.txt
See title.
Thank you kind stranger for guide feedback.
=> all: explain in short detail what Luma3DS configuration even is

_pages/en_US/troubleshooting.txt
=> fix troubleshooting :)

_pages/en_US/a9lh-to-b9s.txt, _pages/en_US/checking-for-cfw.txt, _pages/en_US/faq.txt, _pages/en_US/finalizing-setup.txt, _pages/en_US/installing-boot9strap-(fredtool).txt, _pages/en_US/installing-boot9strap-(usm).txt, _pages/en_US/move-emunand.txt, _pages/en_US/seedminer.txt, _pages/en_US/troubleshooting.txt, _pages/en_US/uninstall-cfw.txt
Reverts hacks-guide/Guide_3DS#2153
=> Revert "faq+troubleshooting: collapsibles"

_pages/en_US/troubleshooting.txt
1. its called essential.exefs
2. steps are part of finalizing
thank you
=> remove troubleshooting for missing essentials.exefs

_pages/en_US/finalizing-setup.txt, _pages/en_US/godmode9-usage.txt, _pages/en_US/move-emunand.txt, _pages/en_US/region-changing.txt
https://github.com/d0k3/GodMode9/blob/master/resources/gm9/scripts/GM9Megascript.gm9#L32 its ??, not ???
=> remove one # because outdated

_pages/en_US/seedminer.txt
people may think they have to add the bot if they never did it before(neat case but no downsides right)
=> add parantheses around re

_pages/en_US/troubleshooting.txt
missing boot.3dsx no longer crashes, now loads forever :)
=> update troubleshooting to match the new luma version

_pages/en_US/finalizing-setup.txt, _pages/en_US/godmode9-usage.txt, _pages/en_US/troubleshooting.txt
- Added link to the troubleshooting page in Finalizing Setup + GodMode9 Usage
- Fixed a h2wtest link and moved some sections that were misplaced
=> Fixed some stuff

assets/js/selecting.js
SSLoth should check minor version, not major version
=> fix SSLoth checker

_pages/en_US/get-started.txt
=> fix some small issues

assets/js/selecting.js
=> revert and dont revert at the same time

_includes/consoleVersionSelect.html, assets/js/selecting.js
apparently we want to keep safecerthax
=> Readd Old 3DS/New 3DS model table

_pages/en_US/bannerbomb3.txt
I've occasionally seen people ask if the SD card should be removed at this point, even though there is no step to remove it. Maybe a reassurance would be good here.
=> bannerbomb3: mention that the SD should stay in the PC

_pages/en_US/include/3ds-11.17.txt
=> its 10.2.1, not 11.0, people like being smart

_pages/en_US/updating-firmware-(kor-twn).md, _pages/en_US/updating-firmware-(new-3ds).md, assets/js/selecting.js
-  EUR/JPN N3DS 11.14-11.15,: super-skaterhax
- TWN 11.15, KOR O3DS 11.15: seedminer
=> Add system update pages for super-skaterhax and seedminer

_pages/en_US/bannerbomb3-(legacy).md, _pages/en_US/include/bb3-prep.md, _pages/en_US/include/fredtool-prep.md, _pages/en_US/include/fredtool-restore-dsconn.md, _pages/en_US/include/fredtool-write-flipnote.md, _pages/en_US/installing-boot9strap-(fredtool-legacy).md, _pages/en_US/seedminer-(mii).md, _pages/en_US/site-navigation.txt, assets/js/selecting.js
♫ Everybody was Mii Seedmining ♫
♪ GPUs fast as lightning ♪
♬ In fact, it was a little bit frightening ♬
♫ But they mined with expert timing ♫
This PR adds mii mining methods to fill a temporary hole left by 11.17. Split from #2269. This involves three new pages:
- Seedminer (Mii)
- BannerBomb3 (11.14 / 11.15)
- Installing boot9strap (Fredtool, 11.14 / 11.15)
- BB3 and Fredtool's actual webpages are named "bannerbomb3-(legacy)" and "installing-boot9strap-(fredtool-legacy)", respectively
Site navigation has been updated accordingly. JS and TOC changes pending.
Mii mining is proposed to be the automatic method for:
- O3DS on 11.15
- USA N3DS on 11.14, 11.15
=> add mii mining

_pages/en_US/installing-boot9strap-(safecerthax).txt
=> Fix missed change for new camera button check

_pages/en_US/installing-boot9strap-(kartdlphax).txt
Kartdlp hax just released to fix O3DS 11.17, and I wanted to call dibs on getting the commit in
=> Reflect kartdlphax 1.3.2

_pages/en_US/homebrew-launcher-(super-skaterhax).txt
=> super-skaterhax: add note on actual folder to copy for USA consoles

_pages/en_US/installing-boot9strap-(hbl-usm).txt, _pages/en_US/installing-boot9strap-(kartdlphax).txt
- XML is having issues
- We don't need it anyway
- Also sync kartdlphax with USM in some cases
=> Don't copy the entire slotTool folder, just the 3dsx

_pages/en_US/region-changing.txt
do lily forget to git add _pages/en_US/region-changing.txt?
=> re: ~~ctrtransfer/~~region-changing: add faketik

_pages/en_US/bannerbomb3-fredtool-(twn).txt, _pages/en_US/homebrew-launcher-(pichaxx).txt, _pages/en_US/homebrew-launcher-(steelhax).txt
=> Fix (missed) different branch of seedminer ref links to avoid confusion

assets/js/selecting.js
* add version validator to prevent ppl from entering version like 1.17
* blacklist 11.17 for K/C/T
=> Version validation

_pages/en_US/404.txt, _pages/en_US/410.txt
=> add a redirect for pages we've removed

_pages/en_US/seedminer-(mii).txt
-These years are guesses and not proven
-Im afraid people with Old 2DS start at 2011 because its on the backplate and so on
=> manufacturing years ong

_pages/en_US/troubleshooting.txt
It was a bit difficult wording this (since they can also end up here by failing to do MSET9), but I think it works well enough.
=> Update Seedminer troubleshoot to account for MSET9

_pages/en_US/installing-boot9strap-(super-skaterhax).txt
i dont want to have to deal with this in assistance anymore
this page isn't going to last much longer though, anyways
=> Add "Text" inline troubleshooting for skaterhax

_pages/en_US/troubleshooting.txt
Added steps for error 4 for mset9
Added SD formatting for error 04 for MSET9
=> Add Error 04 and macOS SD format links to MSET9 Troubleshooting

_pages/en_US/include/ctrnand-datayeet.txt
Amazing reason, I know.
Probably isn't needed, but it stuck out to me now that Seedminer is out of use(and dead in four months time)
=> CTRTransfer: Change wording because I didn't like it

_pages/en_US/installing-boot9strap-(mset9-play-store).txt
MSET9 Android's "Alternate Exploits" link was never updated. So, here you go.
=> Redirect Alternate Exploits to wiki

_pages/en_US/move-emunand.txt
=> Remove FBI from what's needed in move emunand page

_pages/en_US/godmode9-usage.txt
Changes as of https://wiki.hacks.guide/w/index.php?title=3DS:GodMode9/Usage&oldid=5139
=> godmode9-usage: sync with wiki page

_pages/en_US/finalizing-setup.txt
Clicking config.ini will actually download it this time
=> finalizing-setup: Force(?) download config.ini

_pages/en_US/ctrtransfer.txt
- Do a NAND backup before doing CTRTransfer
=> NAND backups in CTRTransfer

_pages/en_US/include/ctrnand-datayeet.txt
=> Change SysNAND Writing Permissions Required

_pages/en_US/ctrtransfer.txt, _pages/en_US/region-changing.txt
Waiting on a consensus from #guide-meta (and I probably messed up the ordering for the downloads)
=> Move torrent downloads to What You Need

_pages/en_US/include/winerror234.txt
=> Numbers weren't auto incremented

_pages/en_US/troubleshooting.txt
User's using the "unable to update" troubleshooting guide when already modding may be using Pretendo.
=> Add Pretendo to update troubleshooting

_pages/en_US/installing-boot9strap-(super-skaterhax).txt
=> skaterhax: clarify what date is the correct date

docs/troubleshooting.md
this pull request brings world peace by adding the kor tid for home menu theme data and removing an extraneous angle bracket
=> add kor tid & remove extraneous angle bracket

docs/a9lh-to-b9s.md, docs/installing-boot9strap-(hardmod).md, docs/installing-boot9strap-(ntrboot).md, docs/installing-boot9strap-(safecerthax).md, docs/installing-boot9strap-(soundhax).md, docs/installing-boot9strap-(ssloth-browser).md, docs/restoring-updating-cfw.md, docs/uninstall-cfw.md, docs/updating-b9s.md
=> treewide: change files needed

docs/_include/ctrnand-datayeet.md
The CTRTransfer image that is to be deleted is in `/gm9/in` now
=> CTRTransfer image is in /gm9/in now

docs/_include/troubleshooting-sb9si-bin.md, docs/_include/troubleshooting-sb9si-common.md, docs/_include/troubleshooting-sb9si-firm.md, docs/troubleshooting-a9lh-to-b9s.md, docs/troubleshooting-mset9.md, docs/troubleshooting-ntrboot.md, docs/troubleshooting-safecerthax.md, docs/troubleshooting-soundhax.md, docs/troubleshooting-ssloth-browser.md, docs/troubleshooting-super-skaterhax.md, docs/troubleshooting-updating-b9s.md
Fix troubleshooting for pages that use .firm of sb9si
=> Fix troubleshooting for pages that use .firm of sb9si

docs/formatting-sd-(windows).md
sync with wiki: use SD Card Formatter for all cards
not sure if section I step 13 need some more tweak
=> sync with wiki: use SD Card Formatter for all cards

docs/el_GR/get-started.md, docs/el_GR/installing-boot9strap-(soundhax).md, docs/get-started.md, docs/hu_HU/get-started.md, docs/hu_HU/installing-boot9strap-(soundhax).md, docs/installing-boot9strap-(soundhax).md, docs/installing-boot9strap-(super-skaterhax).md, docs/it_IT/get-started.md, docs/it_IT/installing-boot9strap-(soundhax).md, docs/ko_KR/get-started.md, docs/ko_KR/installing-boot9strap-(soundhax).md, docs/pt_BR/get-started.md, docs/pt_BR/installing-boot9strap-(soundhax).md, docs/public/assets/js/common.js, docs/public/assets/js/link-common.js, docs/public/assets/js/selecting.js, docs/public/assets/js/skater-link.js, docs/public/assets/js/soundhax-link.js
Automatically provide correct soundhax/super-skaterhax files when navigated from version selector.
NOTE: this breaks translations
=> Automatically replace link to file accordingly to selected version

docs/key-information.md
The wording seemed a bit sloppy -- phrasing everything as an FAQ might make things easier to understand?
Also added a note to redirect DSi-wielding people, but that might end up being more confusion than it's worth
=> key-info: update headers

docs/_include/nand-backup.md, docs/_include/sysupdate.md
should hopefully fix issue #2524 i think? i hope i did this right...
=> fix funky wunky troubleshooting links

docs/troubleshooting-mset9.md
=> troubleshooting-mset9: missing pyfatfs troubleshooting

docs/public/gm9_scripts/uninstall_cfw.gm9, docs/public/gm9_scripts/uninstall_hax.gm9, docs/uninstall-cfw.md
Tested on old 3DS, need test on new 3DS to ensure nothing breaks
=> Hotfix for uninstall cfw script brick issue

docs/formatting-sd-(windows).md
Emphasize that all size need SD Formatter
=> Emphasize that all size need SD Formatter

docs/installing-boot9strap-(safecerthax).md, docs/installing-boot9strap-(ssloth-browser).md
as requested by ajl721, ive added a few warnings in the proxy sections of the ssloth and safecerthax exploits to ensure users dont skip the section
=> add proxy warnings to ssloth + safecerthax

docs/installing-boot9strap-(mset9-play-store).md
=> mset9-play-store: fix mset9 zip name

docs/.vitepress/i18n/en_US.js
=> Copyright 2025

docs/installing-boot9strap-(mset9-cli).md, docs/installing-boot9strap-(mset9-play-store).md
Particularly on-console steps don't really have any reason to be different between mobile and desktop versions.
=> mset9-*: sync some text

docs/finalizing-setup.md
adds brief description about what pretendo is and does, as well as the official guide to the end of finalizing
=> finalizing-setup.md: add notes about pretendo to finalizing-setup

docs/key-information.md
Added mention of Android tablets and iPhones/iPads to key-information.md (iOS added due to MSET9-iOS)
=> Add more devices to supported devices list
